### ISSUE TITLE
Permissions for Accounts

### ISSUE THREAD

**Issue by micahp2** [totem-technologies/totem#225]
As a system administrator I need a way to assign permissions or roles to accounts such that there can be different features and user flows seen by different people.

To get started, I would like there to be three account permission levels:
- Customer - the default level for any new accounts that are created
- Keeper - an elevated level that will require additional validation
- Administrator - a superuser type account that has to be made manually

The plan would be to have the app and system check these permissions and use them to look up the required Account States #226 in order to guide the customer down the right path. Some additional details follow:

1. At the end of the new account creation process new customers are always assigned the Customer permission
2. The only way to get (currently) a Keeper or Administrator permission is for someone to manually edit the database
3. Some additional method is needed to connect these permissions to the account states so that Customers only see customer items, Keepers only see Keeper items, etc.

**Comment by schalky** [comment]
Make use of the 'userAccountState' collection for users to write role data.
This has to be managed by a cloud function as that collection is read only for users.

**Comment by ansells** [comment]
I'm looking at this as more like "rights" or "permissions" that would only be set on a more granular basis rather than as "roles". The idea is that any function that requires a certain permission would check it it is available in the account status and block access if it is not available. So, a role like "keeper" would actually encompass a set of permissions like `create-circle`, `keep-circle`, etc. An "admin" role may or may not include these roles, but would have ones like `edit-user`, `ban-user`, etc.
Basic functions of joining circles and such would not require permissions so by default a user is created with an empty permission set.

**Comment by micahp2** [comment]
As long as we can associate these permissions into a person-friendly grouping like the roles above, I am fine. If that's not what you meant, we can talk further.

**Comment by blopker** [comment]
Some thoughts on the advantages:

1. No augment there! Although it does come with some caveats (like the size limit and all data is sent with all auth requests), but it does seem like they promote this method.
2. I looked into it, and the Firestore rules can also access arbitrary data in Firestore: https://firebase.google.com/docs/firestore/security/rules-conditions#access_other_documents. It might be slower? It's definitely more verbose, but we can also create reusable functions in the rules file to make that cleaner.
3. This is true, however, changes to this data is not propagated like other data. I only refreshes under specific circumstances: https://firebase.google.com/docs/auth/admin/custom-claims#propagate_custom_claims_to_the_client. This was not obvious to me and could cause some weird behavior if the client is waiting for their claims to get updated. Although, there is a force-refresh workaround.
4. Since the claim data is always sent with the auth data, this may actually add overhead, depending on how we use it. I suspect that generally clients will only request the data once on startup, which they have to get other data anyway, and not really get it again unless it changes. So, functions will have to make an extra request every time they run, however they are close to the data and will already have an open connection. Even if the function code doesn't have to get the same document for other reasons anyway, I suspect the overhead will be minimal.

So yeah, I'm on the fence. However, I don't think it matters all that much at this point, and it should be relatively easy to switch between methods since it's just a json blob.

**Comment by ansells** [comment]
1. I think the 1000-byte limit should be fine for quite some time. Even if our permission strings are each 10 characters long that allows more than 90 permissions before we hit the limit. 
2. Yes, you can access other data in Firestore rules, but that generally means an extra DB read for every single check.
3. We would have to implement some force-refresh in the client for changes to the claims, but even using plain data the client would still probably need to react to a data change because we want the permissions to be used in the client UI as well as for access restrictions.
4. Ultimately, it boils down to the overhead of some extra DB reads vs some extra data in the auth token.

I am also a bit on the fence as well, but I am leaning towards doing it the "official" way but keeping the permissions more course and closer to the "roles" initially since we don't have that many permissions to model right now. Then as we need more and perhaps finer-grain permissions we can decide if we need to change the mechanism.

At any rate, I plan to use the `accountState` collection to store the permissions so it will just be a matter of whether they are read directly by client and cloud functions or whether editing them triggers a process to update the auth.

**Comment by blopker** [comment]
Sounds good. In either case, we could consider putting the data in an interface similar to what's described here: https://auth0.com/blog/flutter-authentication-authorization-with-auth0-part-4-roles-permissions/ (further down the bottom).

**Comment by ansells** [comment]
I've got the basic mechanism for this implemented in a draft PR:
- https://github.com/totem-technologies/totem/pull/260

I am thinking that we should setup the basic `userAccountState/{uid}` structure when an account is created to make it easier to edit since we don't have any sort of admin UI.

Beyond that, we need to decide what role restrictions and/or UI we want to first implement and if it should be in this ticket or a separate one.

**Comment by blopker** [comment]
Notes: Add 'Keeper' to the user's profile if they are a Keeper.
