### ISSUE TITLE
Better onboarding

### ISSUE THREAD

**Issue by blopker** [totem-technologies/totem#55]
A better onboarding flow in the app, explaining what the app is about how to use it and setting the guidelines. This information could show up at account creation or before a Circle starts.

Possible ideas to include:

- What is Circle
- Wear headphones
- Have a good internet connection
- Turn off notifications
- Get comfortable

**Comment by micahp2** [comment]
For an early take on this, let me come up with a quick and condensed version that can be used to bootstrap the first-time-use experience and focus on just the minimal help needed. We'll focus on the big-ticket items from the recent circle feedback:

- How this thing is different from Zoom
- The mute-by-default nature of Circles
- Receiving the baton, accepting or passing, and mute status
- Quick tips for expected behavior

@blopker anything else that should be there or that should be swapped in instead of this set?

**Comment by micahp2** [comment]
Content to be provided in this format:
  title: "Title of first page",
  body: "Here you can write the description of the page, to explain something...",
  image: Center(
    child: Image.network("https://domaine.com/image.png", height: 175.0),

**Comment by blopker** [comment]
We can also show it during account creation. We used to have a guidelines screen there that I think is just commented out.

For the content itself, maybe talk about confidentiality?

I had a running list of possibilities here as well: https://docs.google.com/document/d/1ZVs0AnAZptAe_kr0D_uHaRUrDohSoysr4aFHoQZJyhc/edit#heading=h.n5s18onknem9
Some may be too much on the woo side for now though.

**Comment by blopker** [comment]
Done!
